### ISSUE TITLE
cannot use  raw-mask as input mask

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#18] opened 2020-12-08 16:14 UTC
I ran SoFiA-2 with S+C enabled and wrote the `raw-mask` to disc. I then gave that `raw-mask` as input mask but got  this error:

```
ERROR: Mask cube must be of 32-bit integer type.
       Terminating with error code 7.
```

Indeed, the  `raw-mask` is saved with  `BITPIX  =  8`.

**Comment by vdhulst** [comment] 2020-12-08 16:32
This is an interesting point. Ideally one would want to be able to read all flavours of the FITS BITPIX mode.

**Comment by SoFiA-Admin** [comment] 2020-12-09 02:01
This is not exactly a bug, but the intended behaviour. The raw mask is binary and therefore able to use 8 bit which saves a lot of memory and allows SoFiA 2 to stay below 2.3 times the input cube size in memory usage. The raw mask was never intended to be written to disk and then read back in again, but it was just meant to be a debugging feature that you had requested a while ago.

If you need to retain all pixels in the mask after source finding, you could instead set up the linker such that no filtering of any kind is performed. If you then write out the regular mask, you will get a 32-bit mask that SoFiA can read again.

In fact, given this possibility, I am starting to wonder why we decided to implement that raw mask feature in the first place? I just did a quick test, and indeed when you set

```
linker.minSizeXY           =  1
linker.minSizeZ            =  1
linker.keepNegative        =  true
```

you actually get a mask that is identical to the raw mask, except that it is a 32-bit mask rather than an 8-bit one. That 32-bit mask can then be read into SoFiA again if needed.

Hence, unless there is a specific reason for keeping the raw mask feature, my suggestion would be to remove it again from SoFiA 2, as it would not appear to provide any extra information or functionality, and the raw mask cannot be read back into SoFiA anyway. Let me know if you agree or disagree with that assessment.

**Comment by paoloserra** [comment] 2020-12-09 06:52
> In fact, given this possibility, I am starting to wonder why we decided to implement that raw mask feature in the first place?

Because it is a lot more intuitive and modular that if a user is interested in saving an S+C binary mask they do not need to run any merging and do not need to fiddle with merging parameters that they  are not interested in.

Your suggestion is a workaround, but why force users to follow a workaround when it would be a lot more transparent and intuitive to simply allow users to save the mask after S+C, and be able to re-use it in a subsequent SoFiA run? 

or the same reason, I  think users should be allowed to switch off merging. We've had a similar discussion in the past and we might want to reconsider this. See #2.

> Hence, unless there is a specific reason for keeping the raw mask feature

There isn't one if we allow users to disable the linker and save the mask straight out of S+C. See #2.

**Comment by SoFiA-Admin** [comment] 2020-12-15 07:41
The latest commits (7d04c686ae2e63f2caa22c3ddc61ac0c527fb7c4, 05f3f00d1c1ec0d26bf276e0f3485affc922384e) implement the two features that we agreed on during our meeting on Monday:

1. It is now possible to disable the linker by setting the new `linker.enable` option to `false`. In this case the pipeline will stop after source finding. There is a sanity check to ensure that at least some output gets created prior to linking.
2. The input mask provided to SoFiA 2 can now be of any integer type (8, 16, 32 or 64 bit). The downside of this additional flexibility is extra memory usage (unless the input mask is 32-bit already, in which case no copying is needed and the input mask is used straight away). Hence, SoFiA 2 will now require more memory than 2.3 times the cube size if a non-32-bit input mask is provided.

Please check those changes and let me know if you find any issues. I ran a few basic tests, such as disabling source finding and providing an input mask instead, and SoFiA 2 appears to be behaving as expected.

**Comment by SoFiA-Admin** [comment] 2021-02-08 07:38
As the reported bug appears to have been fully resolved by the aforementioned commits, this issue can now be closed.

**Closed by SoFiA-Admin** 2021-02-08 07:38 UTC
Labels: 3 Medium, Bug
