### ISSUE TITLE
Significant difference between smoothing in SoFIA-1 and SoFiA-2

### ISSUE THREAD

**Issue by paoloserra** [SoFiA-Admin/SoFiA-2#4] opened 2020-04-27 06:39 UTC
I'm finding some significant differences between the output mask of SoFiA-1 and SoFiA-2.

Below I show the raw masks obtained running SoFiA-1 and SoFiA-2 on a test cube which includes a poorly-cleaned source. I convolved the cube with a single SCkernel of size [6,6,3]; scaled the data by the local noise using a [63pix,21chan] window; and applied a 5 sigma threshold. All noise measurements use MAD-negative.

The image below shows the mask of SoFiA-2 in white and the mask of SoFiA-1 with red contours.

![Screen Shot 2020-04-27 at 08 00 27](https://user-images.githubusercontent.com/6591265/80338660-2dcd8080-885d-11ea-8126-914bbb0cfe98.png)

I append below the  full logs of SoFiA-1 and -2.

After noise-scaling, the noise measurement differs only marginally between the two runs: 9.88e-01 in SoFiA-1, 9.914e-01 in SoFiA-2 -- a marginal factor of 1.003 higher. Therefore, if the smoothed cubes were the same, SoFiA-2 should have detected a (marginally) lower fraction of pixels. Yet, SoFiA-1 detects 0.0203% while SoFiA-2 detects 0.028% of all pixels (38% more pixels).

In my opinion this shows that there must  be significant differences between the output of the smoothing algorithms used in SoFiA-1 and -2. I cannot say which one is "more correct". However, in the case shown here, the result of SoFiA-1 is better because it includes less sidelobes in the mask. Not shown here, SoFiA-1 is also better at not including the mosaic edge in  the mask.

Of course some small differences are expected, but in this case I think they are too large.

Unfortunately I am not able to hack the SoFiA-2 code to write the output of a single S+C smoothing step to disc. I think this would be the natural next step of this investigation.

```
Paolos-MacBook-Pro:c2894 pserra$ python ~/Astro/SoFiA/sofia_pipeline.py c2894.par 

--- SoFiA 1.3.3: Running the SoFiA pipeline ----------------------------------

    Using: SoFiA   1.3.3
           Python  2.7.14
           NumPy   1.13.3
           SciPy   1.0.0
           Astropy 2.0.2


--- SoFiA 1.3.3: Reading default parameters ----------------------------------
    Elapsed time: 00:00:00.00 h


--- SoFiA 1.3.3: Reading user parameters -------------------------------------
    Elapsed time: 00:00:00.00 h

Parameters extracted from: c2894.par

--- SoFiA 1.3.3: Loading data cube(s) ----------------------------------------
    Elapsed time: 00:00:00.00 h

Loading cube c2894_sofiatest.fits
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
The data cube has been loaded.
Data cube(s) loaded.

--- SoFiA 1.3.3: Applying input filters --------------------------------------
    Elapsed time: 00:00:00.31 h

    Generating noise-scaled data cube:
      Selecting local noise measurement method.
      Applying median absolute deviation to negative pixels.
      Using grid size of [31 pix , 11 chan ]
      and window size of [63 pix , 21 chan ].
      Interpolating in between grid points (linear).
    Noise-scaled data cube generated.

Input filters applied.

--- SoFiA 1.3.3: Running source finder ---------------------------------------
    Elapsed time: 00:00:07.92 h

Running S+C filter
    Estimating rms on subcube (x,y,z zoom = 1,1,1) ...
    Estimating rms on subcube sampling every 3 voxels ...
    ... Subcube shape is (51, 167, 184) ...
    ... mad rms = 1.00e+00 (data units)

    Elapsed time: 00:00:08.07 h
    Filter 6 6 3 b ...
    Generating noise-scaled data cube:
      Selecting local noise measurement method.
      Applying median absolute deviation to negative pixels.
      Using grid size of [31 pix , 11 chan ]
      and window size of [63 pix , 21 chan ].
      Interpolating in between grid points (linear).
    Noise-scaled data cube generated.

    Estimating rms on subcube (x,y,z zoom = 1,1,1) ...
    Estimating rms on subcube sampling every 3 voxels ...
    ... Subcube shape is (51, 167, 184) ...
    ... mad rms = 9.88e-01 (data units)
    Applying +/- 5.0 sigma detection threshold
Source finding complete.
8,455 out of 41,683,701 pixels detected (0.0203%)
    Elapsed time: 00:00:15.60 h
Reloading data cube for parameterisation
Loading cube c2894_sofiatest.fits
The data cube has been loaded.

--- SoFiA 1.3.3: Writing mask cube -------------------------------------------
    Elapsed time: 00:00:15.72 h


--- SoFiA 1.3.3: Pipeline finished -------------------------------------------
    Elapsed time: 00:00:16.36 h
```

```
pserra@corto:~/Astro/source_finding/c2894$ sofia c2894-2.par 
____________________________________________________________________________

 Pipeline started
____________________________________________________________________________

  Using:    Source Finding Application (SoFiA)
  Version:  2.1.1 (15-Apr-2020)
  CPU:      8 cores available
  Time:     Mon Apr 27 08:05:37 2020

____________________________________________________________________________

 Loading parameter settings
____________________________________________________________________________

  Activating SoFiA default parameter settings.
  Loading user parameter file: 'c2894-2.par'.

  Using all 8 available CPU cores.

____________________________________________________________________________

 Loading data cube
____________________________________________________________________________

  Opening FITS file 'c2894_sofiatest.fits'.
  Reading FITS data with the following specifications:
    Data type:    -32
    No. of axes:  4
    Axis sizes:   551, 501, 151
    Region:       0-550, 0-500, 0-150
    Memory used:  159.0 MB
  Searching for values of infinity.
    No infinite pixel values found.

  Elapsed time: 00:00:00 h
  CPU time:     00:00:00 h

____________________________________________________________________________

 Scaling data by noise
____________________________________________________________________________

  Correcting for local noise variations.
  - Noise statistic:  median absolute deviation
  - Flux range:       negative

    Grid size:    31 x 11
    Window size:  63 x 21

  Measuring noise in running window.
  Progress:  |==================================================| 100%


  Elapsed time: 00:00:01 h
  CPU time:     00:00:04 h

____________________________________________________________________________

 Measuring global noise level
____________________________________________________________________________

  Global RMS:  1.005e+00  (using stride of 41)

  Elapsed time: 00:00:01 h
  CPU time:     00:00:04 h

____________________________________________________________________________

 Running S+C finder
____________________________________________________________________________

  Using the following parameters:
  - Kernels
    - spatial:        6
    - spectral:       3
  - Flux threshold:   5.0 * rms
  - Noise statistic:  median absolute deviation
  - Flux range:       negative

  Using a stride of 41 in noise measurement.

  Smoothing kernel:  [6.0] x [3]
  Correcting for local noise variations.
    Grid size:    31 x 11
    Window size:  63 x 21

  Measuring noise in running window.
  Progress:  |==================================================| 100%

  Noise level:       9.914e-01

  Elapsed time: 00:00:02 h
  CPU time:     00:00:07 h

  0.028% of all pixels detected.

____________________________________________________________________________

 Writing raw binary mask
____________________________________________________________________________

  Creating FITS file: 27apr_mask-raw.fits

  Elapsed time: 00:00:02 h
  CPU time:     00:00:08 h

____________________________________________________________________________

 Running Linker
____________________________________________________________________________

  Progress:  |==================================================| 100%

  Linker status:
   - No. of objects:  8
   - Memory usage:    0.95 kB


  Elapsed time: 00:00:02 h
  CPU time:     00:00:08 h

____________________________________________________________________________

 Reloading data cube for parameterisation
____________________________________________________________________________

  Opening FITS file 'c2894_sofiatest.fits'.
  Reading FITS data with the following specifications:
    Data type:    -32
    No. of axes:  4
    Axis sizes:   551, 501, 151
    Region:       0-550, 0-500, 0-150
    Memory used:  159.0 MB

  Elapsed time: 00:00:02 h
  CPU time:     00:00:08 h

____________________________________________________________________________

 Pipeline finished.
____________________________________________________________________________
```

**Comment by SoFiA-Admin** [comment] 2020-04-27 06:54
For debugging purposes, adding the following line after the smoothing operation in line 3535 of DataCube.c should allow you to write out the smoothed cube to disk:

`DataCube_save(csmoothedCube, "filename.fits", true, true);`

Replace `filename.fits` with a file name of your choice. The first `true` is to enable overwriting of existing files; set this to `false` if you don’t want to risk data loss. Keep the last argument `true` at all times.

Make sure to rerun the `compile.sh` script after any changes to the source code.

**Comment by paoloserra** [comment] 2020-04-27 08:13
```
  Compiling src/DataCube.c
src/DataCube.c: In function ‘DataCube_run_scfind’:
src/DataCube.c:3535:19: error: ‘csmoothedCube’ undeclared (first use in this function)
     DataCube_save(csmoothedCube, "smoothed-debug.fits", true, true);
                   ^
src/DataCube.c:3535:19: note: each undeclared identifier is reported only once for each function it appears in
  Compiling sofia.c
```

**Comment by paoloserra** [comment] 2020-05-18 07:58
The images below show the difference between smoothing with SoFiA-1 and SoFiA-2.

I used a smoothing kernel of 6 pix FWHM along X and Y axes, and no smoothing along the Z axis.

`SoFiA-1 smoothed image`, 1 colour step = 1 sigma:
![Screen Shot 2020-05-18 at 09 46 17](https://user-images.githubusercontent.com/6591265/82187741-298d0400-98ed-11ea-95ac-87b2aed96088.png)

`SoFiA-2 smoothed image`, 1 colour step = 1 sigma (sigma is nearly the same as in the SoFiA-1 smoothed image):
![Screen Shot 2020-05-18 at 09 46 29](https://user-images.githubusercontent.com/6591265/82187750-2c87f480-98ed-11ea-9eb1-d4fe4c8b5bc7.png)

`SoFiA-1 smoothed image minus SoFiA-2 smoothed image`, 1 colour step = 0.1 x sigma of the SoFiA-1 and SoFia-2 smoothed images:
![Screen Shot 2020-05-18 at 09 46 36](https://user-images.githubusercontent.com/6591265/82187749-2bef5e00-98ed-11ea-937f-9c1095707be8.png)

Input cube with, overlaid, contours of the difference `SoFiA-1 smoothed image minus SoFiA-2 smoothed image`, drawn at +/- 0.1 x sigma of the SoFiA-1 and SoFia-2 smoothed images:
![Screen Shot 2020-05-18 at 09 51 09](https://user-images.githubusercontent.com/6591265/82187748-2b56c780-98ed-11ea-9f70-0ae4a3056ffa.png)

Besides the obvious differences, also note that in the SoFiA-2 smoothed image pixels that were NaN in the original cube are now 0. This may affect the noise calculation.

**Comment by paoloserra** [comment] 2020-05-18 14:18
OK, I'm finding much larger differences between SoFiA and Miriad (both for SoFiA-1 and -2) than  between SoFiA-1 and SoFiA-2. So I think @SoFiA-Admin is correct that there are no significant bugs in SoFiA-2's smoothing, and we just have to live with the differences caused by the different smoothing algorithms:

- Miriad smooths with an FFT, see https://www.atnf.csiro.au/computing/software/miriad/userguide/node147.html .
- SoFiA-1 smooths in the image plane with Scipy's gaussian_filter, which truncates the Gaussian at  4 sigma by  default, see https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter.html .
- SoFiA-2 approximates Gaussian smoothing with a sequence of box-smoothing operations (@SoFiA-Admin correct me if I'm mistaken).

`SoFiA-1 minus Miriad`
![Screen Shot 2020-05-18 at 14 42 47](https://user-images.githubusercontent.com/6591265/82214914-ce700700-9916-11ea-99df-1adc8a48f212.png)

`SoFiA-2 minus Miriad`
![Screen Shot 2020-05-18 at 14 42 54](https://user-images.githubusercontent.com/6591265/82214897-ca43e980-9916-11ea-9987-13eae2d4c55b.png)

I'm a little puzzled by the different scale that "emission" seem to have in these images (see also the `SofiA-1 minus SoFiA-2` image above).

**Comment by vdhulst** [comment] 2020-05-18 14:22
It may be useful to also produce a plot of the difference divided by one to the other (or the average of both) smoothed images, so we get a feel for the relative differences.

**Comment by SoFiA-Admin** [comment] 2020-05-19 03:44
Thanks for testing. I had a look at the smoothing output from SoFiA 2 and can confirm that there is nothing unusual and everything looks as expected. For this test, I simply created a 2D image filled with 0 that has the central pixel set to 1, thus imitating a true, noise-free point source. I then applied different smoothing kernels in SoFiA 2 and fitted a Gaussian to the convolved image to check its FWHM and Gaussianity.

I repeated this exercise for two different settings of the maximum number of boxcar iterations that the algorithm is allowed to apply (6 versus 10). As expected, the actual FWHM is very close to the requested kernel size, and generally gets better when more iterations are allowed, as shown below:

![FWHM_error](https://user-images.githubusercontent.com/6572706/82281404-c9b55c80-99c3-11ea-9d93-60db83c2921a.png)

As can be seen, the relative error (FWHM<sub>obs</sub> &minus; FWHM<sub>true</sub>) / FWHM<sub>true</sub> is close to zero in both cases. The only exception occurs if a FWHM < 3 is requested, in which case the algorithm chooses not to convolve at all, as such a small Gaussian apparently cannot be approximated by a series of at least 3 boxcar filters (2 iterations might work, but would produce a triangular filter shape, so I currently don’t allow that).

Likewise, the profile shape is fairly close to Gaussian, again with a better approximation for a larger permitted number of iterations:

![profiles](https://user-images.githubusercontent.com/6572706/82281419-d043d400-99c3-11ea-98e7-39c6740045e8.png)

Here, the black, dashed curve is a true Gaussian with the same FWHM and amplitude as the blue curve (maximum of 10 boxcar iterations). As you can see, the blue curve is an excellent approximation of a Gaussian, but even the orange curve (maximum of 6 boxcar iterations) is still very close to a Gaussian.

So, overall the algorithm is producing the expected outcome, and the differences between Miriad, SoFiA&nbsp;1 and SoFiA&nbsp;2 indeed seem to be due to different algorithms being applied by each software, each of which provides a different approximation to true Gaussian convolution.

In the interest of speed, I prefer to keep the maximum iterations set to 6, as there is little improvement for larger values that wouldn’t justify the significant increase in processing time. As mentioned before, the minimum number of boxcar iterations is currently set to 3 to avoid the triangular shapes resulting from just 2 iterations of boxcar filtering.

**Comment by RussellJurek** [comment] 2020-05-19 04:41
Is the smoothing parallelised yet?

**Comment by SoFiA-Admin** [comment] 2020-05-19 04:51
@RussellJurek Yes, it is fully multi-threaded at this stage.

**Comment by paoloserra** [comment] 2020-05-19 05:40
> As can be seen, the relative error (FWHMobs − FWHMtrue) / FWHMtrue is close to zero in both cases. The only exception occurs if a FWHM < 3 is requested

Is the spike at ~20% relative error at FWHM = 3 pix? I'm asking because that's a commonly used kernel.

**Comment by SoFiA-Admin** [comment] 2020-05-19 05:52
@paoloserra Yes, that’s for 3 px. The actual kernel is close to 3.5 px in this case.

**Comment by SoFiA-Admin** [comment] 2020-05-28 02:29
As discussed here and at our meeting on Monday, the observed differences are likely caused by different algorithms used to approximate Gaussian smoothing. Such differences are to be expected and of no concern, as the individual algorithms appear to be working correctly. I will therefore close this issue now.

**Closed by SoFiA-Admin** 2020-05-28 02:29 UTC
Labels: 2 High, Question
